version: "3.9"

networks:
    web-network:

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: php-dev

        networks:
            - web-network

        volumes:
            - ./:/srv/app:rw,cached
            - php_sessions:/sessions
#            - ./node_modules:/srv/app/node_modules:rw,cached

    nginx:
        build:
            context: ./docker/nginx/
            dockerfile: Dockerfile
            target: nginx

        networks:
            - web-network

        volumes:
            - ./:/srv/app:rw,cached
        ports:
            - 80:80

    node:
        build:
            context: ./docker/node/
            dockerfile: Dockerfile
            target: node

        entrypoint: entrypoint

        volumes:
            - ./:/srv/app:rw,cached
#            - ./node_modules:/srv/app/node_modules:rw,cached

        networks:
            - web-network

volumes:
    app_cache:
    php_sessions: