#!/bin/sh

sudo mysql -u root -e "DROP DATABASE IF EXISTS test ;
CREATE DATABASE \`$MYSQL_DATABASE\`;
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASS';
GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\` . * TO '$MYSQL_USER'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED VIA mysql_native_password USING PASSWORD('$MYSQL_ROOT_PASS');
FLUSH PRIVILEGES;
"
